use_frameworks!

platform :ios, '10.0'

target 'iotcamera_Example' do
  pod 'tutk_camera', :path => '../'

  target 'iotcamera_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
